### ISSUE TITLE
Constants not available as Qt attributes

### ISSUE THREAD

**Issue by krisutofu** [jmechnich/intel-power-control#11]
I downloaded your application as an AUR package.

<https://aur.archlinux.org/packages/intel-power-control-git>

However, the package is outdated. I explicitly installed PyQt6 and PyQt6 SIP additionally and it worked. But then, it crashed when the "systray icon" is enabled because it cannot find the color constants under 'Qt'. When I turned the 'Qt.red' into 'Qt.GlobalColor.red' (in the `/usr/bin/intel-power-control` python script) then it works without crashing.

Is there something that I am missing for a normal functioning without hacking? Or are there differences in the PyQt API for Windows and Linux?

**Comment by jmechnich** [comment]
I am sorry, this was an oversight/bug from when I was porting the code to Qt 6. It should be fixed in v1.0.1.

Thanks for reporting!
