### ISSUE TITLE
Temperature values barely visible with dark theme

### ISSUE THREAD

**Issue by krisutofu** [jmechnich/intel-power-control#12]
The thermal zones area in the GUI shows a column Temperature but the values are displayed in black color.

The other font adapts to the OS theme and is displayed in white. Ideally, the temperature values should also be displayed in the main colour of the OS theme.

**Comment by jmechnich** [comment]
You are completely right that this is not ideal. The text color was hard-coded in certain places to either black (default) or red (above threshold) for "historic" reasons.

Starting from tag v1.0.1, the default text color is taken from the QGuiApplication.palette() which should reflect the current theme settings.

Thanks for reporting!
