### ISSUE TITLE
GPU clock limits get overridden by boost clock limit

### ISSUE THREAD

**Issue by Hermanio** [jmechnich/intel-power-control#2]
I found that GPU clock limits do not work, under load the GPU still hits a max of 1250MHz in my case.

When looking through the code I fould no trace of `gt_boost_freq_mhz` which should be changed in a fashion similar to `gt_max_freq_mhz`.

Here is an example:

Max clock speed is set to 350. Boost clock speed is left untouched (default in my case is 1250). When the GPU encounters load, the GPU clock speed is increased to 1250MHz because the boost clock speed overrides the max clock speed.

Solution:

either change the boost clock speed together with max clock speed or offer separate limiter for boost clock speeds.

Relevant Unix StackExchange question:
https://unix.stackexchange.com/questions/404049/how-to-stop-intel-hd4000-from-running-at-max-clock-speed

**Comment by jmechnich** [comment]
Interesting, I hadn't noticed the API changes so far. The latest code supports boost frequency (you have to check 'Sync boost to maximum' in order to have the boost frequency throttled automatically).

Please let me know if that works for you.

**Comment by Hermanio** [comment]
Seems to work fine now, thank you!
