### ISSUE TITLE
add dirname (argv [0]) to suidhelper search path

### ISSUE THREAD

**Issue by mralusw** [jmechnich/intel-power-control#3]
Most users will run intel-power-control from the git directory. And it will fail to find the helper, of course, since the git directory isn't in the `PATH`.

As a simple workaround, add the `dirname` of the Python program to the searched dir list in which():
```
     else:
-        for path in os.environ["PATH"].split(os.pathsep):
+        for path in os.environ["PATH"].split(os.pathsep) + [os.path.dirname (sys.argv[0])]:
             path = path.strip('"')
```

(normally, it would be easier to modify `os.environ["PATH"]` directly at the beginning of `main()`, but since you're setting `suidhelper` directly in a class constructor, `which()` will be called before `main()`)

**Comment by jmechnich** [comment]
Hi there,

thanks for your comment.
I am not convinced that this is what most users will or should do. You would still have to run make and set the suid bit manually for this to work. If that is something you want to do, you can set an alias, write a wrapper or just add '.' to your PATH.
