### ISSUE TITLE
No module named 'sip'

### ISSUE THREAD

**Issue by ayoubelmhamdi** [jmechnich/intel-power-control#8]
```
Traceback (most recent call last):
  File "/bin/intel-power-control", line 7, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'
```

**Comment by jmechnich** [comment]
I have added PyQt5-sip to the dependencies, can you try again?

**Comment by ayoubelmhamdi** [comment]
there is another problem, python can't find it,

perhaps, we should import `snip` from `PyQt5`
### FIX
```diff
--- a/intel-power-control
+++ b/intel-power-control
@@ -4,7 +4,7 @@
 import argparse
 import os
 import re
-import sip
+from PyQt5 import sip
 import subprocess
 import sys
```

**Comment by ayoubelmhamdi** [comment]
@jmechnich  there is another problem, python can't find it,

perhaps, we should import `snip` from `PyQt5`
### FIX
```diff
--- a/intel-power-control
+++ b/intel-power-control
@@ -4,7 +4,7 @@
 import argparse
 import os
 import re
-import sip
+from PyQt5 import sip
 import subprocess
 import sys
```

**Comment by jmechnich** [comment]
Thanks for your suggestion and sorry for not looking into the problem properly.

The actual solution was to remove the dependency on `sip` altogether as the program was crashing at the call to `sip.delete`.
Using `sip` was sort of a hack I had to use when I wrote the code back in the day using Qt4 IIRC. Using a Qt-internal function seems to work now just as well.

Please let me know if the most recent version is working now (or just close this issue).

**Comment by jmechnich** [comment]
This should be fixed. Closing due to lack of feedback.
