### ISSUE TITLE
cannot overclocking the iGPU uhd770

### ISSUE THREAD

**Issue by chopin1998** [jmechnich/intel-power-control#9]
i have a question,

my CPU is 13700k which ship with a UHD770,  by default its max freq is 1600Mhz

i have set it value to **2000MHz** in BIOS, but reboot to linux, boost freq still limit to 1600Mhz.

![image](https://user-images.githubusercontent.com/643792/213490411-ada26877-e1e9-49b1-a6c7-bf8f4e6723c9.png)

how can i overclock it? thank you!

**Comment by jmechnich** [comment]
Sorry for the late reply!

The values are read from `/sys/class/drm/card*/gt_*_mhz`. You can check yourself what they contain using e.g. `grep . /sys/class/drm/card*/gt_*_mhz`.

It is possible that overclocking the CPU does not overclock the GPU as well, or that you have to do sth to "allow" the GPU to be overclocked on Linux (e.g. set a parameter to a kernel module, i.e. `i915`).

**Comment by jmechnich** [comment]
@chopin1998  have you made some progress on this? Unfortunately, I don't have access to a machine of this caliber. In any case,  `intel-power-control` is not an overclocking tool. It will just manipulate the sysfs entries that I have mentioned in my previous post.

**Comment by chopin1998** [comment]
seem latest guc firmware donot allow overclock (unless some specialy command send i guess).


thank you all the same!
